### ISSUE TITLE
Implement bullets as a sprite class

### ISSUE THREAD

**Issue by rickardo-cornelli** [PontusLin/ProjInda#12]
- Should be its own class
- Should travel in the same direction the player is facing, at a constant speed(can implement air resistance later)
- When a player is hit with a bullet, their lives should decrease by 1. (Can be implemented with spritecollide)

**Comment by PontusLin** [comment]
- Should be its own class
- Should travel in the same direction the player is facing, at a constant speed(can implement air resistance later)
are done, only 
- When a player is hit with a bullet, their lives should decrease by 1. (Can be implemented with spritecollide)
left

**Comment by rickardo-cornelli** [comment]
everything is fixed
