### ISSUE TITLE
Fix movement bug

### ISSUE THREAD

**Issue by rickardo-cornelli** [PontusLin/ProjInda#13]
As of now, the player cannot move along obstacles. Instead, the player is warped in a very glitchy manner.
- [x] update move method
- [x] need to update collision handling so that the player can move along side obstacles etc

**Comment by rickardo-cornelli** [comment]
Done! However, now there's an invisible wall. It is less urgent though. The game is much more playable, even though the invisible wall is a bit frustrating and confusing.

**Comment by PontusLin** [comment]
invisible wall is removed due to cropping of asset files.
