### ISSUE TITLE
Implement multiplayer mode

### ISSUE THREAD

**Issue by rickardo-cornelli** [PontusLin/ProjInda#6]
- [x] Have one player control with arrows and shoots with shift. The other player moves tank with WASD and shoots with space.
- [x] Add player lives as ints(for example 3 lives)
- [x] Display lives on screen and player name/indication
- [x] When a player is shot, they lose on life. Have them respawn on a random location on the map(but not inside a wall)

**Comment by PontusLin** [comment]
done
